import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(
    page_title="Tier 4: Single-Cell Transcriptomics Showcase | GenomeTech Studio",
    page_icon="🧬",
    layout="wide"
)

st.markdown("""
<style>
    .stApp {
        background: radial-gradient(circle at top right, #1e1b4b 0%, #0f172a 60%, #020617 100%);
        color: #f1f5f9 !important;
        font-family: 'Inter', sans-serif;
    }
    .tier-header {
        background: linear-gradient(90deg, #3b82f6 0%, #1d4ed8 100%);
        padding: 2rem;
        border-radius: 16px;
        margin-bottom: 2rem;
        border: 1px solid rgba(96, 165, 250, 0.4);
    }
    .showcase-card {
        background: rgba(30, 41, 59, 0.7);
        border: 1px solid rgba(59, 130, 246, 0.3);
        border-radius: 12px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
    }
</style>
""", unsafe_allow_html=True)

# Navigation header back to main website
if st.button("← Back to GenomeTech Studio"):
    st.markdown('<meta http-equiv="refresh" content="0;url=https://bhumikasihare.github.io/genometech-studio/">', unsafe_allow_html=True)

st.markdown("""
<div class="tier-header">
    <span style="background: rgba(255,255,255,0.2); padding: 4px 12px; border-radius: 999px; font-size: 0.8rem; font-weight: bold;">TIER 4 SHOWCASE DASHBOARD</span>
    <h1 style="color: white; margin-top: 10px;">Single-Cell Transcriptomics Profiling (Demo Pipeline)</h1>
    <p style="color: #93c5fd; margin: 0;">Interactive demonstration of our end-to-end scRNA-seq Seurat analysis pipeline, featuring automated quality control, clustering, cell-type annotation, and UMAP projections.</p>
</div>
""", unsafe_allow_html=True)

# Layout split: Left side explains the pipeline steps / code metrics; Right side displays live demo results
col1, col2 = st.columns([1, 1.5], gap="large")

with col1:
    st.markdown('<div class="showcase-card">', unsafe_allow_html=True)
    st.markdown("### 🧬 Pipeline Architecture & Methods")
    st.markdown("""
    This showcase demonstrates the robust computational steps executed in our **Tier 4 Single-Cell Profiling** pipeline:
    
    1. **Matrix Processing & QC:** Filtering low-quality cells (<200 features) and mitochondrial gene contamination (<5%).
    2. **Normalization & HVG Selection:** Log-normalization and identification of top 2,000 highly variable genes (HVGs).
    3. **Dimensionality Reduction:** Principal Component Analysis (PCA) followed by Shared Nearest Neighbor (SNN) graph-based clustering.
    4. **Marker Gene Identification:** Wilcoxon rank-sum test to discover signature differentially expressed genes per cluster.
    5. **Cell-Type Annotation:** Automated mapping against reference peripheral blood mononuclear cell (PBMC) atlases.
    """)
    st.markdown("---")
    st.markdown("**Deliverables Included in Tier 4:**")
    st.markdown("- Cleaned Seurat Object (`.rds`)")
    st.markdown("- High-Resolution Vector SVG UMAP & Heatmap Plots")
    st.markdown("- Marker Gene Excel/CSV Tables (`avg_log2FC`, `p_val_adj`)")
    st.markdown('</div>', unsafe_allow_html=True)

with col2:
    st.markdown('<div class="showcase-card">', unsafe_allow_html=True)
    st.markdown("### 📊 Live Seurat Clustering Results (Demo Dataset)")
    st.markdown("Explore the annotated cell clusters and marker gene signatures generated by our automated script:")
    
    # Mock single cell cluster data table
    mock_clusters = pd.DataFrame({
        "Cluster ID": [0, 1, 2, 3, 4, 5],
        "Cell Type Annotation": ["CD4+ T Cells", "CD8+ Cytotoxic T", "CD14+ Monocytes", "B Cells", "NK Cells", "Dendritic Cells"],
        "Top Marker Genes": ["IL7R, CD3D", "CD8A, GZMB", "LYZ, S100A9", "MS4A1, CD79A", "NKG7, GNLY", "FCER1A, CST3"],
        "Cell Count": [4120, 2890, 2450, 1120, 890, 310],
        "Mean Expression (AvgLog2FC)": [2.41, 2.18, 1.95, 2.67, 2.12, 1.84]
    })
    
    st.dataframe(mock_clusters, use_container_width=True)
    st.markdown('</div>', unsafe_allow_html=True)

# Full-width section below for interactive UMAP visualization
st.markdown('<div class="showcase-card">', unsafe_allow_html=True)
st.markdown("### 🔬 Interactive UMAP Projections Viewer")
st.markdown("Demonstration of 2D manifold approximation showing distinct cellular populations color-coded by cluster identity:")

# Generate realistic mock scatter plot data for UMAP preview
np.random.seed(42)
cluster_names = ['CD4+ T Cells', 'CD8+ Cytotoxic T', 'CD14+ Monocytes', 'B Cells', 'NK Cells']
data_list = []
for c_name in cluster_names:
    center_x = np.random.uniform(-5, 5)
    center_y = np.random.uniform(-5, 5)
    x = np.random.normal(center_x, 1.2, 50)
    y = np.random.normal(center_y, 1.2, 50)
    df_part = pd.DataFrame({'UMAP_1': x, 'UMAP_2': y, 'Cell Type': [c_name]*50})
    data_list.append(df_part)

umap_demo_df = pd.concat(data_list, ignore_index=True)
st.scatter_chart(umap_demo_df, x='UMAP_1', y='UMAP_2', color='Cell Type', use_container_width=True)
st.markdown('</div>', unsafe_allow_html=True)